### PR TITLE
feat: node os module

### PR DESCRIPTION
**Pull request by Puellaquae**
Implement node os module in js, https://github.com/WasmEdge/WasmEdge/issues/1535 .
Module name "os" has been used by quickjs, and in windows "node:os" is not a valid name, so I named "nodeos" temporarily.
`os.constants` and `os.networkInterfaces()` return empty data.
`os.getPriority()`, `os.loadavg()` and `os.userInfo()` return fake data.
`os.cpus()` is unimplemented and will throw error.
 `os.totalmem()` always return 4294967296 (4GiB, as much as wasm32 can use) and `os.freemem()` is `totalmem() - memory.size`.

### CODE REVIEW

**Review by L-jasmine — COMMENTED** [review]
rename `nodeos.js` to `os.js`

**Comment by Puellaquae** [comment]
> rename `nodeos.js` to `os.js`

Will this name not conflict with this quickjs built-in os module?

**Comment by Puellaquae** [comment]
Or, should re-export built-in os module in os.js?

**Comment by L-jasmine** [comment]
> > rename `nodeos.js` to `os.js`
> 
> Will this name not conflict with this quickjs built-in os module?

Oh, I forget it.

https://github.com/second-state/wasmedge-quickjs/blob/a471968c0f1b0df28d59f2a4d08d71b2ae0d9a7d/src/quickjs_sys/mod.rs#L369

quickjs built-in os module is registered by this line.

modify it to `js_init_module_os(ctx, "qjs:os\0".as_ptr() as *const i8); ` just ok.

**Comment by Puellaquae** [comment]
I rebase my branch to latest main, rename nodeos.js to os.js, and re-export qjs:os in os.js.

**Review by L-jasmine — APPROVED** [review]

**Pull request merged**
